In [1]:
from __future__ import division
import sys
home_dir=!echo "$HOME"
sys.path.insert(2,home_dir[0]+'/iPyNb/NERSC_Import') #make sure you have iPyNb checked out from AD
from pyROOT_import import *
from ROOT import TH2D, TFile, TBranch
import numpy as np

In [2]:
IQ_data=sio.loadmat('Run04_correction_iq.mat')

In [40]:
def dict_from_mat(mat_data):
    a=[]
    keys=[]
    S=dict()
    for key in mat_data.keys():
        if key[0]!='_':
            a.append(mat_data[key])
            keys.append(key)
            S.update([(key,mat_data[key])])
    keys=array(keys)
    
    #S=dict([keys,a])
    
    return S

In [53]:
S=dict_from_mat(IQ_data)
a=np.ndarray(S['detcenter_iq_times'],dtype=float64)

TypeError: only length-1 arrays can be converted to Python scalars

array([[  1.40979348e+09,   1.41080268e+09,   1.41125118e+09,
          1.41176388e+09,   1.41220398e+09,   1.41262860e+09,
          1.41348336e+09,   1.41418116e+09,   1.41433740e+09,
          1.41446532e+09,   1.41481746e+09,   1.41514848e+09,
          1.41600390e+09,   1.41634362e+09,   1.41678180e+09,
          1.41696006e+09,   1.41745122e+09,   1.41782256e+09,
          1.41808512e+09,   1.41827364e+09,   1.41867600e+09,
          1.41902568e+09,   1.42073250e+09,   1.42110042e+09,
          1.42144812e+09,   1.42177866e+09,   1.42195566e+09,
          1.42246818e+09,   1.42291428e+09,   1.42306722e+09,
          1.42323660e+09,   1.42378710e+09,   1.42439880e+09,
          1.42500498e+09,   1.42574334e+09,   1.42634328e+09,
          1.42699062e+09,   1.43302122e+09,   1.43317638e+09,
          1.43361042e+09,   1.43421240e+09,   1.43455104e+09,
          1.43518566e+09,   1.43578644e+09,   1.43602680e+09,
          1.43638476e+09,   1.43697156e+09,   1.43758542e+09,
        

In [56]:
for ii,(key,val) in enumerate(IQ_data.iteritems()):
    print(key,shape(val))

('s2_y_bins', (1, 68))
('s1_xyz_map_bottom', (1, 40))
('z_dep_bottom_values', (68, 3))
('s1_xyz_map_all', (1, 40))
('s1_map_all', (1, 68))
('s2_x_bins', (1, 68))
('s1_xyz_z_bins', (1, 40))
('det_z_center', (1, 68))
('s1_xyz_x_bins', (1, 40))
('s2xy_iq_times', (1, 68))
('s1xyz_iq_times', (1, 40))
('s2_map_all', (1, 68))
('s2_norm_z_iqs', (1, 68))
('s1xy_iq_times', (1, 68))
('detcenter_iq_times', (1, 68))
('s2_map_bottom', (1, 68))
('s1z_iq_times', (1, 68))
('det_x_center', (1, 68))
('s1_x_bins', (1, 68))
('s1_y_bins', (1, 68))
('__version__', ())
('z_dep_both_values', (68, 3))
('s1_xyz_y_bins', (1, 40))
('__header__', ())
('__globals__', (0,))
('s2_norm_iqs', (1, 68))
('s2z_iq_times', (1, 68))
('s1_map_bottom', (1, 68))
('det_y_center', (1, 68))


In [80]:
IQ_data['s2_y_bins'][0][10]

array([[-23.5, -20.5, -17.5, -14.5, -11.5,  -8.5,  -5.5,  -2.5,   0.5,
          3.5,   6.5,   9.5,  12.5,  15.5,  18.5,  21.5]])

In [61]:
key_1D=['s2_y_bins','s2_x_bins','det_z_center','s2xy_iq_times','s2_norm_z_iqs','s1xy_iq_times',
       'detcenter_iq_times','s1z_iq_times','det_x_center','s1_x_bins','s1_y_bins','s2_norm_iqs',
        's2z_iq_times','det_y_center']

In [41]:
shape(IQ_data['s2_map_all'][0][0])
shape(IQ_data['s2_y_bins'][0][0])[0]
#shape(IQ_data['s2_map_all'][0][0])

1

In [377]:
f = TFile('Run04_IQs.root', "recreate") 
t = TTree("tree", "Run04IQs_1D")
n=[]
vals=[]
ii=0
for (key,val) in IQ_data.iteritems():

    if (key in key_1D): #only do 1 D
        vals.append(val[0])
        #n.append(np.array([0],dtype=float64))
        n.append(np.zeros((68,size(val[0][0]))))
        t.Branch(key, n[ii], key+'/d') #d is float64
        ii=ii+1


num_branches=ii
num_elements=size(val)

for jj in range(num_elements):
    for kk in range(num_branches):
        for nn in range(size(vals[kk][jj])):
            if (size(vals[kk][jj])==1):
                n[kk][jj]=vals[kk][jj]
            else:
                if (shape(vals[kk][jj])[0]==1):
                    n[kk][jj][nn] =vals[kk][jj][0][nn]
                else:
                     n[kk][jj][nn] =vals[kk][jj][nn]
        t.Fill()
f.Write()
f.Close()
    

In [369]:
n[1][1]

array([-23.5, -20.5, -17.5, -14.5, -11.5,  -8.5,  -5.5,  -2.5,   0.5,
         3.5,   6.5,   9.5,  12.5,  15.5,  18.5,  21.5])

In [256]:
for (key,val) in IQ_data.iteritems():
    if (key in key_1D): #only do 1 D
        print(key,val)

('s2_y_bins', array([[ array([[-23.5, -20.5, -17.5, -14.5, -11.5,  -8.5,  -5.5,  -2.5,   0.5,
          3.5,   6.5,   9.5,  12.5,  15.5,  18.5,  21.5]]),
        array([[-23.5, -20.5, -17.5, -14.5, -11.5,  -8.5,  -5.5,  -2.5,   0.5,
          3.5,   6.5,   9.5,  12.5,  15.5,  18.5,  21.5]]),
        array([[-23.21   , -19.6301 , -16.0501 , -12.4701 ,  -8.89017,  -5.31021,
         -1.73024,   1.84972,   5.42968,   9.00964,  12.5896 ,  16.1696 ,
         19.7495 ]]),
        array([[-23.5, -20.5, -17.5, -14.5, -11.5,  -8.5,  -5.5,  -2.5,   0.5,
          3.5,   6.5,   9.5,  12.5,  15.5,  18.5,  21.5]]),
        array([[-23.1173  , -19.3518  , -15.5863  , -11.8209  ,  -8.05538 ,
         -4.28991 ,  -0.524444,   3.24103 ,   7.0065  ,  10.772   ,
         14.5374  ,  18.3029  ,  22.0684  ]]),
        array([[-23.5, -20.5, -17.5, -14.5, -11.5,  -8.5,  -5.5,  -2.5,   0.5,
          3.5,   6.5,   9.5,  12.5,  15.5,  18.5,  21.5]]),
        array([[-23.5, -20.5, -17.5, -14.5, -11.5,  -8.5,  -

<h1> Test root file </h1>

In [378]:
rootarr=root2array('Run04_IQs.root')
rootarr

array([(-23.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 161.4641, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 161.4641, 1409793481.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 161.4641, 1409793481.0, 7.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 161.4641, 1409793481.0, 7.5, 1409793481.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 161.4641, 1409793481.0, 7.5, 1409793481.0, 1409793481.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 161.4641, 1409793481.0, 7.5, 1409793481.0, 1409793481.0, 1409793481.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 161.4641, 1409793481.0, 7.5, 1409793481.0, 1409793481.0, 1409793481.0, -0.5432, 0.0, 0.0, 0.0, 0.0, 0.0),
       (-23.5, -23.5, 161.4641, 1409793481.0, 7.5, 1409793481.0, 1409793481.0, 14